
name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: eshoponweb-primary-app-service    # set this to the name of your Azure Web App
  SECONDARY_AZURE_WEBAPP_NAME: eshoponweb-secondary-app-service    # set this to the name of your Azure Web App
  PUBLIC_API_AZURE_WEBAPP_NAME: eshoponweb-public-api-app-service    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0'                 # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
        
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish src/PublicApi/PublicApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/publish/PublicApi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: public-api
          path: ${{env.DOTNET_ROOT}}/publish/PublicApi

  deploy-public-api:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-publicapi-webapp.outputs.webapp-url }}

    steps:
      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: public-api

      - name: Deploy to PublicApi Azure Web App
        id: deploy-to-publicapi-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PUBLIC_API_AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
